apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80 # The port the service will listen on
      targetPort: 5000 # The port your container is listening on (EXPOSE 5000)
  type: LoadBalancer # Exposes the service externally (or NodePort/ClusterIP for internal)